### Create new user
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
  "firstName": "Nehemie",
  "lastName": "Mombanga",
  "username": "6nehemie@test.com",
  "password": "testtest"
}

### Google OAuth SignIn
GET http://localhost:3000/auth/google

### Sign in user
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  "username": "6naomie@test.com",
  "password": "testtest"
}

### Get current user
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoibmVoZW1pZS5tYmdAZ21haWwuY29tIiwiaWF0IjoxNzI0NjYxNzc2LCJleHAiOjE3MjQ3NDgxNzZ9.c8Br38oENgbIoUgqaDOtRviasdgA7KNTQRQJKvlwMkQ